### ISSUE TITLE
Support for SQL

### ISSUE THREAD

**Issue by lenisko** [giampaolo/pyftpdlib#323]
Hello there,
Is there any chance for this great library to support sqlite/mysql?

What I'm really looking for is a way to add/remove users while server is working.

Greetings!

**Comment by lenisko** [comment]
I have created basic support for sqlite,
https://github.com/lenisko/pyftpdlib/blob/master/pyftpdlib/authorizers.py

maybe someone want take a look at it. Oh and it's not safe for production I guess...

**Comment by giampaolo** [comment]
Hello there. This is a fairly easy task but I don't think it's generic
enough so that it can be included in pyftpdlib code base. If you search
through previous discussions you'll find different examples on how to
subclass base DummyAuthorizer and make db queries.

**Comment by lenisko** [comment]
Okay, thank you for explanation.
I managed to get it working, but still I think that SQL should be available to all, it's common.

Greetings

**Comment by giampaolo** [comment]
Yes but your tables and columns have their own names and the logic a user
is supposed to be authenticated can be different than just comparing two
strings and the ORM you're using is not the only one out there. Should we
support django orm? Sqlalchemy? Should we require them during installation?
And most importantly, what api should we provide so that it can satisfy
most (all?) use cases? There are many questions and when you don't have
the  answers to most of those questions (I don't) it usually means the
problem cannot be generalized to a point that most of the people will be
happy with the final solution.

**Comment by lenisko** [comment]
Thanks for comprehensive explanation. At many points you are right.
