### ISSUE TITLE
How to send error to client on on_file_received ?

### ISSUE THREAD

**Issue by akoumjian** [giampaolo/pyftpdlib#326]
This may be ignorance on my part with respect to how FTP works. I have some custom logic on whether a user has used all their alloted space (not based on the filesystem). I am inserting a check using the handler's ``on_file_received`` method. I would like to send an error message to the client when this happens. 

Currently I have something like this:

```python
            message = '452 Out of Private Storage. Please Upgrade.'
            self.respond(message)
```

That doesn't seem to work. Is such a task possible? Thank you.

**Comment by giampaolo** [comment]
Sorry for replying so late. It is probablt **too** late but here goes my reply anyway. 
No, that's not possible because `on_file_received` is called after the server already sent the response to client.
Instead you should override `DTPHandler.handle_close` method and implement the replying logic in there.
