### ISSUE TITLE
threaded ftpserver get exception on ftp_CWD

### ISSUE THREAD

**Issue by PonyPC** [giampaolo/pyftpdlib#368]
because threaded ftpserver share one path info
and the os.chdir() in ftp_CWD will get exception on multi requests
Not found such directory

**Comment by cthrax** [comment]
I believe I am seeing this problem without being multi-threaded.

There is a note on handlers.py around line 2526:


```
        # Note that if for some reason os.getcwd() gets removed after
        # the process is started we'll get into troubles (os.getcwd()
        # will fail with ENOENT) but we can't do anything about that
        # except logging an error.
```

Looking in _compat, it appears os.getcwd is used in both cases, so why is the compat handle needed? Couldn't os.getcwd be called alleviating the problem?

**Comment by lurch** [comment]
> Looking in _compat, it appears os.getcwd is used in both cases

Look more closely... ;-)  The PY3 version uses `os.getcwd` and the PY2 version uses `os.getcwdu` (notice the extra `u` on the end).

If you're getting the error on a non-multi-threaded server, then it looks like it might be a race condition i.e.
 1. `ftp_CWD` stores away the current working-dir
 1. then it attempts to temporarily chdir to the `path` in `self.fs` (to check if the permissions are correct)
 1. and finally it chdirs back to the original working-dir it saved in step 1.

If there's some external process that deletes the current working-dir between steps 1 and 3, then maybe that's the cause of your exception?

**Comment by cthrax** [comment]
@lurch ah, you are exactly right, sorry for that. That's a good suggestion, but I don't have anything that manipulates the paths.

I am however running this constantly. The error is only presents after a time (I'm not sure if it's actually time related or transaction related, I am running a test right now to see if I can induce the issue by transaction count).

When it does present, every call to CWD directory fails with "No such file or directory". My suspicion up to this point is the handle to os.getcwd has gone stale somehow. Because as soon as the server restarts, everything is fine again.

Going based on my assumption of a stale handle, I wonder if changing _compat to create a passthrough function would solve the issue. 

ie. instead of:

`getcwdu = os.getcwdu`

Something more like:


```
    def getcwdu():
        return os.getcwdu()
```

Thoughts?

**Comment by lurch** [comment]
> My suspicion up to this point is the handle to os.getcwd has gone stale somehow

Sounds a bit unlikely. Are you sure that it isn't the filesystem underneath pyftpdlib that's playing up? Or maybe pyftpdlib is running out of filehandles somewhere?

**Comment by giampaolo** [comment]
The problem is not osgetcwd/u(). The problem is clearly stated by the error "No such file or directory". It occurs on CWD command because the first thing it does before changing directory is figuring out what the current **process** directory is:
https://github.com/giampaolo/pyftpdlib/blob/4aeb1810a830cd977e74620c245ae28f9e3b304d/pyftpdlib/handlers.py#L2536
...in order to "get back to it" immediately after attempting `os.chdir()` a bit later.
Note that I'm not talking about the user directory but the directory you were in when you started the Python process. It seems that directory was removed some time after you started the FTP process.
The fix is to re-create it and not delete it anymore.

**Comment by cthrax** [comment]
@giampaolo Thanks for the clarification. My deployment process does remove the directory the process was started under, but I do restart the process on deployment, maybe there's a timing issue there. I will investigate that.

**Comment by giampaolo** [comment]
That is an unusual use case. You can work around that by overwriting `pyftpdlib.handler.getcwdu` like this:

```
import pyftpdlib.handlers
pyftpdlib.handlers.getcwdu = lambda: ""
```

That will have the consequence that the process working directory will constantly change every time a user CWD into a directory.
It is kind of unusual for any system process to change cwd so often but it won't represent a problem unless you use relative paths for referencing log or configuration files from within your code. If that's the case then use explicit absolute paths (e.g. `"/var/log/ftpd.log"` instead of `"ftpd.log"`).

**Comment by cthrax** [comment]
Ah, that's an interesting idea as well. I will play with them both and see what works best. Thanks again for the help!

**Comment by giampaolo** [comment]
You're welcome.
