### ISSUE TITLE
Canceling a transfer in FIleZilla, on_file_received is called

### ISSUE THREAD

**Issue by baracoder** [giampaolo/pyftpdlib#461]
I have registered a handler for the `on_file_received` event. According to the documentation, it is called, when a file was transferred successfully. If I cancel a transfer in FileZilla, the event still gets called.
I am not sure if FileZilla or pyftpdlib is to blame

**Comment by giampaolo** [comment]
I would say this depends on what filezilla (client) is doing. If filezilla just `close()`s the data socket then the server (correctly) interprets it as "file transfer is finished". That is what the FTP protocol dictates in case of uploads (from client to server) as per RFC-959. The correct way for filezilla to interrupt a transfer and make the server aware of it would be by using ABOR command. You can easily figure that out by looking at server logs. Run server in DEBUG mode:
http://pyftpdlib.readthedocs.io/en/latest/tutorial.html#debug-logging
...and if you don't see "ABOR" being sent by client then it's filezilla's "fault".
I say "fault" because the reason for filezilla NOT to send ABOR is probably because many FTP servers are unable to handle it correctly, so maybe they just decided to `close()` the data connection.

**Comment by baracoder** [comment]
Thank you for the reply @giampaolo.
I have tested it with debug logging enabled and I am not seeing `ABOR` instead i see `close()` and `STOR` in the logs, even though filezilla shows `Error:	File transfer aborted by user after transferring 2.1 KB in 2 seconds` in the console.
